version: '3.8'

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=database_test
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./.scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres_db

volumes:
  pgdata:
