version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: authentication_db
    ports:
      - '3306:3306'
    volumes:
      - ./.scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_network
    container_name: mysql_db

networks:
  mysql_network:
    driver: bridge
